Documentation:
  Enabled: false

AllCops:
  Exclude:
    - db/schema.rb

  RunRailsCops: true

Style/InlineComment:
  Description: 'Avoid inline comments.'
  Enabled: false

Style/Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#utf-8'
  Enabled: false

Style/ExtraSpacing:
  Description: 'Do not use unnecessary spacing.'
  Enabled: true

Style/IfUnlessModifier:
  MaxLineLength: 120

Style/WhileUntilModifier:
  MaxLineLength: 120

Metrics/LineLength:
  Max: 120
  # To make it possible to copy or click on URIs in the code, we allow lines
  # contaning a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https
